### ISSUE TITLE
channel message -> price list

### ISSUE THREAD

**Issue by abtahizadeh** [halon176/h-crypto-price-bot#39]
Can you add an option to send the price list on the channel?

Also I think the option of alarms in numerical form can be good

Alert the user whenever the numbers reach
BTC: set Alarm : 25800 min 26300 max

**Comment by halon176** [comment]
Hi! Maintaining a price list sounds like a great idea, but it comes with a caveat – it requires a database. While I plan to introduce one, I also aim to ensure that deployment remains feasible for those who cannot host a database themselves. This presents a significant challenge.

To clarify, as of now, the bot doesn't keep track of operating channels or any settings, all of which would necessitate a database.

As for price alerts, I don't believe it's feasible. Such calls consume the free API calls provided by CoinGeco or other services. Implementing alerts would require regularly checking current prices at a substantial interval, exhausting the monthly pool of available calls, which I'd like to avoid.
